#!/bin/sh
#挂在文件系统
mount -a

chmod +x etc/init.d/rcS
#使用内存文件系统

mkdir /dev/pts/
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotlug

mdev -s

#设置ip
#/sbin/ifconfig eth0 192.168.1.17 #nfs 不需要

#挂在/etc/fstab中的文件系统

mount -a
exec /etc/rc.local


